compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  //git.gameloft.org/api/v4/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_DOWNLOAD_TOKEN}"

npmScopes:
  sai_deployment:
    npmRegistryServer: "https://git.gameloft.org/api/v4/packages/npm/"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
